return {
	{
		key         = "room1_extra",
		segment     = "room1_extra",
		blockers    = { "WallCut_room1_extra" },
		displayName = "Доп. комната",
		emoji       = "🚪",
		price       = 150,
		requires    = nil,
	},
	{
		key         = "stairs",
		segment     = "stairs",
		blockers    = { "CeilingPlug_Stairs" },
		displayName = "Лестница",
		emoji       = "🪜",
		price       = 200,
		requires    = nil,
	},
	{
		key         = "floor2",
		segment     = "floor2",
		blockers    = {},
		displayName = "Второй этаж",
		emoji       = "🏠",
		price       = 300,
		requires    = "stairs",
	},
	{
		key         = "floor2_room1",
		segment     = "floor2_room1",
		blockers    = { "WallCut_floor2_room1" },
		displayName = "Комната 2 эт.",
		emoji       = "🛏",
		price       = 200,
		requires    = "floor2",
	},
	{
		key         = "basement_lab",
		segment     = "basement_lab",
		blockers    = { "FloorCut_basement_lab" },
		displayName = "Подземная лаба",
		emoji       = "🧪",
		price       = 400,
		requires    = nil,
	},
}
